### ISSUE TITLE
-

### ISSUE THREAD

**Issue by pkcktkksh98** [Hyradus/DeepLandforms-YOLOv5#1]

**Comment by pkcktkksh98** [comment]
I just noticed that YOLOv5 has an extra value compared to YOLOv8, in its .txt file. Is the extra value represent the center of the bounding box? 
[YOLOv5_example.txt](https://github.com/Hyradus/DeepLandforms-YOLOv5/files/10495356/YOLOv5_example.txt)
[YOLOv8_example.txt](https://github.com/Hyradus/DeepLandforms-YOLOv5/files/10495362/YOLOv8_example.txt)

**Comment by Hyradus** [comment]
Hi, 

I don't know if you have edited the issue and title with a blank comment, but looking at the original issue, it seems that the error is in the function used to convert the YOLO results into a dataframe.
I haven't used yet the v8 but despite having the same type of results I changed the original v5 code in order to save the *confidence* as an additional value.
So, it is possible that something changed in the results and thus my functions are not compatible anymore.

* Could you provide an example of the results?
* Did you used YOLO v8 from ultralytics?

**Comment by pkcktkksh98** [comment]
Hi,

Yes I did, I thought I could deleted it. Sorry for the inconvenience. I was trying to use your code for converting it into shapefile. From my observation, YOLO v8 is using the same labeling format as YOLO v5, the text file that was save from my YOLO v8 output was missing another value, so I read your code back, looking for the missing value. Apparently I was missing the Confidence value in the txt file. In the CLI for running the prediction script, I did not set the save_conf as true, below is the example CLI.

`!yolo detect predict model=best.pt imgsz=1200 source="Ladang_Badak" save_txt=True save_conf=True`

```
Ultralytics YOLOv8.0.11 🚀 Python-3.10.6 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4042MiB)
Fusing... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
WARNING ⚠️ --img-size [1200] must be multiple of max stride 32, updating to [1216]
image 1/130 /home/kazu/ultralytics/Ladang_Badak/LadangBadak_1.tif: 1216x1216 30.0ms
image 2/130 /home/kazu/ultralytics/Ladang_Badak/LadangBadak_10.tif: 1216x128 43.8ms
image 3/130 /home/kazu/ultralytics/Ladang_Badak/LadangBadak_100.tif: 1216x128 38.3ms
...
image 130/130 /home/kazu/ultralytics/Ladang_Badak/LadangBadak_99.tif: 1216x1216 29.8ms
Speed: 1.0ms pre-process, 29.5ms inference, 0.8ms postprocess per image at shape (1, 3, 1216, 1216)
Results saved to /home/kazu/ultralytics/runs/detect/predict5
42 labels saved to /home/kazu/ultralytics/runs/detect/predict5/labels
```

the output location will be in the terminal and the folder will contain the detected image with labels in .txt file.

**Comment by pkcktkksh98** [comment]
So in conclusion, your conversion code is still applicable if the txt file is the same format as YOLO v5 (`<object-class> <x-center> <y-center> <width> <height><confidence>`)

**Comment by Hyradus** [comment]
Great! Thanks for the update. I'll close this issue.
